### ISSUE TITLE
Create homepage for the website

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#111]
When a user is not logged in the platform, they will visit the homepage of the website.
We will provide information about the content.

**Comment by overeha** [comment]
Here are the colors
Here is the page

and figma link
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid-Stam-Acasa?node-id=4%3A0

![colors](https://user-images.githubusercontent.com/45068169/78404293-c24e1580-7606-11ea-9bc4-5823993b91ff.png)
![Stam Acasa - homepage nelogat](https://user-images.githubusercontent.com/45068169/78404295-c417d900-7606-11ea-8189-d249c2d27bfd.png)

**Comment by RaduCStefanescu** [comment]
I would suggest not putting the registration form in the homepage.
Let's keep the homepage without the registration form and we add a register link in the menu, as it is now.

**Comment by dragosrobertn** [comment]
Happy to pick this one up. Can someone pinpoint me to the components they think I should use/reuse for this?

Thanks.

**Comment by surdu** [comment]
@dragosrobertn You should use the [share component](https://github.com/code4romania/taskforce-fe-components/tree/master/src/components/social-share) for the share thingy, the [hero component](https://github.com/code4romania/taskforce-fe-components/tree/master/src/components/hero) for the page title.

Please see the [already existing home page](https://github.com/code4romania/stam-acasa/blob/develop/frontend/src/components/Home/index.js) for an example on how a page should be structured. Come to think about it, this is the page that you also need to modify for this issue.

Also please explore our [share components storybook](https://taskforce-fe-components.now.sh) for more components that you might need for this and in the future.

**Comment by dragosrobertn** [comment]
As per @RaduCStefanescu's comment, I will not be adding a registration form.
