### ISSUE TITLE
Customize backend assessment endpoint

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#113]
The component developed as part of #20 will make a call in the backend for the contents of the assessment form.

We need to create a new assessment controller, that will return the JSON contents of the 2 assessments:
- if the user does not have the profile filled in, we return the initial assessment
- if the user already completed his profile, we return the recurrent assessment

**Comment by andorremus** [comment]
Having a go at this now, should there be an assessment service that the controller calls to get the assessment?

**Comment by RaduCStefanescu** [comment]
Hi @andorremus 
Currently the Form API implements 
- `GET /api/form` - returns all the forms for a user
- `POST /api/form` - receives the results of a form

We need to create a new endpoint `GET /api/form/version` that returns:
- https://github.com/code4romania/stam-acasa/tree/develop/jsondata/q1.json - if the user does not have a profile filled in
- https://github.com/code4romania/stam-acasa/tree/develop/jsondata/q1a.json - if the user already has the profile filled in

We should implement this check using an assessment service, so yeah, it makes sense to have a service. Let me know if I answered your question.

**Comment by andorremus** [comment]
Un-assign this for now and I’ll pick it up later if nobody’s on it

**Comment by RaduCStefanescu** [comment]
Moving this one to backlog, as @andorremus is working on a different task

**Comment by serbandin** [comment]
would like to work on this item.
