### ISSUE TITLE
Send daily emails to users that have an verified account in the platfom

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#116]
We need to send twice a day an email to a users that have an account in the platform.

We need to enhance the scheduling service developed in #64 to send emails to users twice a day, at 9:00 and 18:00

**Comment by cosminpopescu14** [comment]
l-as lua eu :)

**Comment by RaduCStefanescu** [comment]
@cosminpopescu14 please talk to Andrei Balaci he is working on #64

**Comment by RaduCStefanescu** [comment]
Looking over the code and the latest changes, this one seems to be fixed.
Closing it.
