### ISSUE TITLE
Enhance email service to implement worker pool

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#118]
As part of the platform we will need to send many daily emails.
We need to enhance the email service to run multiple workers that will 
- consume the messages of the queue
- distribute the messages to a worker pool that will be sending the emails

**Comment by sudo-robert** [comment]
I can work on this item
Any more details on this, should it have a configurable number of workers?

**Comment by RaduCStefanescu** [comment]
Hey @sudo-robert 
We are going to have to send large number of emails, so yes, having a configurable number of workers, would help a lot.
