### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#119]
We need to create email templates for sending emails:
- account confirmation template
- daily assessment template
- state entity template

We need to create an enum that will be added to the request sent to the email service. Based on the enum the email service will know which template to use.

**Comment by irinel-nistor** [comment]
Salut, as vrea sa lucrez la task-ul asta. Am cateva nelamuriri. Din ce inteleg se va incarca in functie de enum un template din folderul specificat in configuration, la cheia "TemplateFolder", corect?
Avem fisierele html care vor fi folosite drept template?

**Comment by RaduCStefanescu** [comment]
salut! da, exact, avem o lista de templates, si fiecare template ar tb sa aiba un enum asociat. catre email service vine doar acel enum. putem sa plecam sa construim frameworkul pentru asta, sa construim templates si vin cu contentul dupa ce il avem?
