### ISSUE TITLE
Enhance assessment answers service with historic results

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#120]
The assessment service built as part of #53 needs to be enhanced to return historic answers of a user. We should return the history up to the last 4 days of filled in answers.

**Comment by andreimole** [comment]
pot sa iau eu asta?

**Comment by andreimole** [comment]
pare ca e un endpoint in api care intoarce istoricul formularelor completate

**Comment by RaduCStefanescu** [comment]
Da, exista un endpoint in FormController si functionalitatea e implementata deja in FormService. Am sa inchid acest issue. Multumesc de ajutor @andreimole
