### ISSUE TITLE
Create profile for people in care

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#123]
As a user of the platform I need to add people in my care to my account.

Checkout the UX for the full description of the fields that need to be entered
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=1383%3A899

This is similar to #121

**Comment by adascaliteiradu** [comment]
Can I?

**Comment by surdu** [comment]
@adascaliteiradu all yours ;)
