### ISSUE TITLE
Enhance history of assessments with new UX

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#126]
We need to enhance the page for displaying the user assessment history with the new UX.
The initial page is built as part of #54 
This is the new UX
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=1383%3A3657

**Comment by VeronicaM** [comment]
@alinaMihai si eu vom lucra pe acest issue.
