### ISSUE TITLE
Counties/cities endpoints

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#127]
When a user completes his profile - they need to fill in their county/cities.
We need to have this information in the database and expose it through the API.

**Comment by andorremus** [comment]
Where do we get the cities from? Would another controller with a route to get all counties (parent) + cities (children) suffice?

**Comment by surdu** [comment]
@RaduCStefanescu do we have a similar endpoint in any of our other products that @andorremus can draw inspiration from ?

**Comment by RaduCStefanescu** [comment]
yes! the way I see it, we have a static list, that I can import from another project, that is a simple map holding:
- id
- county
- city
We save this information in the database or serve it statically from a file. I would prefer the information in the database.
We then create a new controller, that exposes 2 endpoints - one for getting the list of counties and one that returns the list of cities given a certain county.

**Comment by andorremus** [comment]
Ok, thanks, assign this to me as well please

**Comment by gheorghelupu17** [comment]
[NomenclatorRVM.zip](https://github.com/code4romania/stam-acasa/files/4432563/NomenclatorRVM.zip)

**Comment by RaduCStefanescu** [comment]
Based on the files above, let's import this data in the database and expose a controller to return the data.

**Comment by RaduCStefanescu** [comment]
We decided and moved all the functionality in frontend. Thank you very much for your help @andorremus
