### ISSUE TITLE
Allow frontend to use runtime ENVIRONMENT variables 

### ISSUE THREAD

**Issue by bvizureanu** [code4romania/stam-acasa#140]
the docker container as it is right now need the URLs and other configurable data to be passed in at build time.

We need the "compiled" frontend app to consume the environment variables that have been set at runtime in the container. 

either nginx or node runtime is acceptable for the runtime container. 
the frontend image will contain only the `build` folder of the frontend app not all the sourcecode.

**Comment by CristiHabliuc** [comment]
awesome. I'll take this, I'll use nginx since I see it's already used in the Dockerfile

**Comment by CristiHabliuc** [comment]
> I'll use nginx since I see it's already used in the Dockerfile 

Scratch that, was blinded by the comment leftover. I made the adjustments so that it does the config as usual and still use node inside the docker image.

I also:
- moved config urls into a separate file
- added examples to the README
