### ISSUE TITLE
Create "Terms and Conditions" page

### ISSUE THREAD

**Issue by cipick** [code4romania/stam-acasa#141]
As a user I want to read about how my cookies and other sensitive data is handled by the website due to GDPR regulations before creating an account.

**Comment by cipick** [comment]
Can we use the content from https://rezultatevot.ro/web/politica-de-confidentialitate and https://rezultatevot.ro/web/termeni-si-conditii to build up this page?

**Comment by RaduCStefanescu** [comment]
@overeha do we need a `Terms and conditions` page for this project? Can you please let us know?

**Comment by cipick** [comment]
![image](https://user-images.githubusercontent.com/6429818/78505610-43c7b400-777d-11ea-949b-ec5534d5e4c5.png)
@RaduCStefanescu i saw that when you are creating an account there is a checkbox with a link to `Privacy policy` or `Terms and conditions`

**Comment by dragosrobertn** [comment]
I can pick this one up once we get confirmation of:
- Whether we need Terms and Conditions
- The content that is meant to go on the page
- The url path under which it should go (e.g. `/termeni-si-conditii`)
- If we should link to it from any of the following:
  - Header menu 
  - Footer menu

**Comment by RaduCStefanescu** [comment]
Good point everyone.
I will come back with an answer.

**Comment by RaduCStefanescu** [comment]
Hi everyone.
We have updated the `Terms and conditions` page, you can see the content attached here:
[Termeni si conditii - jurnal medical.pdf](https://github.com/code4romania/stam-acasa/files/4702057/Termeni.si.conditii.-.jurnal.medical.pdf)

**Comment by RaduCStefanescu** [comment]
This one is closed in #448
