### ISSUE TITLE
Create filterable table component

### ISSUE THREAD

**Issue by surdu** [code4romania/stam-acasa#145]
Sortable table component will be used on most daashboard pages:
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=145%3A16

**Default state**
<img width="959" alt="Screen Shot 2020-04-06 at 12 31 33 PM" src="https://user-images.githubusercontent.com/11520795/78544306-99926f80-7802-11ea-88ed-413dc3a61c86.png">

**Clicked state**
<img width="887" alt="Screen Shot 2020-04-06 at 12 30 58 PM" src="https://user-images.githubusercontent.com/11520795/78544339-a747f500-7802-11ea-8bf9-f83675a0dabc.png">

**Comment by maloun96** [comment]
I will take it

**Comment by surdu** [comment]
Fixed in #148
