### ISSUE TITLE
Cache email templates in email service

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#156]
Improve the performance of the Email Service by caching the templates, so the service does not read the files from disk everytime we need to send an email.

**Comment by abalaci** [comment]
Should the caching happen in memory, or do we want something distributed, like Redis?

**Comment by irinel-nistor** [comment]
I would like to work on this task, if you didn't want to do it first @abalaci

**Comment by abalaci** [comment]
That’s alright, @irinel-nistor, you can have it if you really wanted it.

**Comment by RaduCStefanescu** [comment]
Heya! 
The caching should happen in memory, we will only have a few templates that we will use.
I have no idea who should I assign this one to, but I will go with @irinel-nistor I guess. It's all yours!
