### ISSUE TITLE
AssessmentNotificationsDispatch should use the EmailRequestModel

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#161]
Currently the AssessmentNotificationsDispatch uses the AssessmentNotification when sending requests to the Email Service. This needs to be changed to the EmailRequestModel.

**Comment by idormenco** [comment]
which queue should it use ?

**Comment by RaduCStefanescu** [comment]
The regular email queue that we use for all the requests.

**Comment by irinel-nistor** [comment]
Could I pick this up? @idormenco do you want to work on it?

**Comment by idormenco** [comment]
@irinel-nistor you can have it

**Comment by irinel-nistor** [comment]
It is not clear for me what values we should add to the EmailRequestModel (eg Address, Temlpate). Should it be Address = user.Email, Template = "dailyAssesment", PlaceholderContent = {"name", user.Name}?

**Comment by RaduCStefanescu** [comment]
Yes, that sounds about right
- Address = user.Email
- Template = DailyAssessment
- PlaceholderContent = { "name", user.Name + " " + user.Surname}
