### ISSUE TITLE
User creates account

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#17]
The first page that a user navigates to in the website is the Create account page.

![Group 416](https://user-images.githubusercontent.com/15039873/77779662-8b528f80-705b-11ea-8172-d57251ceaecd.png)

The user will insert all the information required for creating an account, the form needs to send the data to the backend API. The endpoints will be delivered soon.

**Comment by AndreiMitrea** [comment]
@RaduCStefanescu I would like to take this task. Thank you!

**Comment by AndreiMitrea** [comment]
@RaduCStefanescu So this page should be the landing page, right?

**Comment by RaduCStefanescu** [comment]
nope, this is the landing page
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=0%3A1
this is just the contul meu page - where a user will create his account

**Comment by AndreiMitrea** [comment]
Got it.

**Comment by RaduCStefanescu** [comment]
This is being handled in #121 so I will close it.
