### ISSUE TITLE
Integrate API calls in historic results components

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#170]
Currently the `Profilul meu` page displays the history of assessments and profile for user and family members.
The data in the components is dummy data.
The components need to use the endpoints to retrieve user and familiy profile, and assessment history:
- `/api/Profile`
- `/api/Profile/family`
- `/api/Form`

**Comment by teodoradima** [comment]
can I take this one?  🙏

**Comment by surdu** [comment]
@teodoradima All yours!

**Comment by RaduCStefanescu** [comment]
Go for it @teodoradima !
Let us know if you have any questions.

**Comment by teodoradima** [comment]
Would this also close issue #181?

**Comment by RaduCStefanescu** [comment]
We still need to do the check if the user has completed his profile or not.
Let's leave it as a sepparate issue for now.
