### ISSUE TITLE
User fills in personal assessment

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#18]
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=39%3A138

**Comment by cipas** [comment]
✌️daca e liber il iau eu

**Comment by RaduCStefanescu** [comment]
The linked issue in fe components is done: code4romania/taskforce-fe-components#106
The component is distributed as part of `V1.0.6` of the fe components.
We can now start working on this issue by including the newly developed component.

**Comment by RaduCStefanescu** [comment]
Should we close this one and open an issue just with the rest of the stuff that needs to be done?
```
Still needs:

Get form data from API
Create authenticated routes (the user can see data only if it is logged in)

**Comment by surdu** [comment]
Created #98
