### ISSUE TITLE
Frontend workflow on first login

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#180]
When a user logs in the application we want to have a clear workflow:
- user completes profile
- user completes profile for people in his care
- user completes initial assessment for himself and people in his care

For this we need to do the following:
- change the order of tabs in the frontend: `Profilul meu`, `Adauga-ti familia in cont`, `Completeaza formularul de evaluare`
- a user can only navigate to the next tab after the information is completed on the current tab

**Comment by RaduCStefanescu** [comment]
@irinel-nistor are you looking into this one?

**Comment by irinel-nistor** [comment]
Yes, i'm looking into it

**Comment by irinel-nistor** [comment]
It is not clear for me if the user should be stopped from going on the 'Completeaza formularul de evaluare' from the 'Adauga-ti familia in cont' tab. Maybe the user lives alone. 
Should it be only stopped from entering the 'Completeaza formularul de evaluare'  if he doesn't have a profile? Only after he creates his own profile from the first tab?

**Comment by RaduCStefanescu** [comment]
We should only let the user navigate to `Completeaza formularul de evaluare` after the user creates a profile in the first tab.
