### ISSUE TITLE
Configure homepage after user completes profile

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#181]
After a user has completed his profile, the `Profilul meu` page should contain historic information about his profile and the assessments a user has completed.
This component has been developed as part of #126

**Comment by irinel-nistor** [comment]
I've seen a comment in another issue(#170 ) Is this what it's left to be done for this item: 
"We still need to do the check if the user has completed his profile or not.
Let's leave it as a sepparate issue for now.". 
I'd like to work on this. (@teodoradima  will help me :D)

**Comment by RaduCStefanescu** [comment]
I am just testing this and I will come back with an answer.
Thank you!

**Comment by RaduCStefanescu** [comment]
I think it would be better to start working on #180 until I get back with an answer on this one.
What do you say @irinel-nistor and @teodoradima ?

**Comment by irinel-nistor** [comment]
On it 🚀

**Comment by CatalinTrand** [comment]
I can take this one

**Comment by RaduCStefanescu** [comment]
All yours @CatalinTrand 
Let us know if you have any questions.

**Comment by RaduCStefanescu** [comment]
This one is already handled it seems, as I see from the latest deployments.
Will close it.
Thank you for your work @CatalinTrand @irinel-nistor
