### ISSUE TITLE
Improve email templates

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#182]
We need to improve the email templates with the following information:
- email subject
- logo for ADR/Code for Romania
- email content
- additional information we need to send an user {name surname}
- signature

**Comment by irinel-nistor** [comment]
I'd like to work on it, but I have some questions:
*email subject, should this be a property added to the EmailRequestModel?
*signature, should this be added to the html template files?
*logo: should it be a file or link referenced int the template files?
*additional info and email content, should this be added in the template html files?

**Comment by RaduCStefanescu** [comment]
- email subject - no, let's keep the same subject depending on the template, we can add it as a property on the template type enum
- signature - yes, add it to the html template
- logo- we have the logos in https://github.com/code4romania/covid-assets - we should add them to the template files
- yes, in the template files, no worries about the content, I will ask the UX team to come up with some good content
