### ISSUE TITLE
Integrate county/city component from taskforce components

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#188]
We need to integrate the components developed as part of https://github.com/code4romania/taskforce-fe-components/issues/147 for the User and Family profile.

**Comment by idormenco** [comment]
on it

**Comment by surdu** [comment]
@idormenco The taskforce component is not merged yet

**Comment by idormenco** [comment]
@surdu i will wait until it is finished and then use it

**Comment by surdu** [comment]
@idormenco component is merged. go go go 🚀

**Comment by RaduCStefanescu** [comment]
Yup, new version available with new component added: https://github.com/code4romania/taskforce-fe-components/releases/tag/v1.0.11

**Comment by idormenco** [comment]
county: [
    { value: 1, label: "Dolj" },
    { value: 2, label: "Bacău" },
    { value: 3, label: "Harghita" },
    { value: 4, label: "Bistrița-Năsăud" },
    { value: 5, label: "Dîmbovița" },
    { value: 6, label: "Suceava" },
    { value: 7, label: "Botoșani" },
    { value: 8, label: "Brașov" },
    { value: 9, label: "București" },
    { value: 10, label: "Brăila" },
    { value: 11, label: "Hunedoara" },
    { value: 12, label: "Teleorman" },
    { value: 13, label: "Covasna" },
    { value: 14, label: "Tulcea" },
    { value: 15, label: "Timiș" },
    { value: 16, label: "Buzău" },
    { value: 17, label: "Prahova" },
    { value: 18, label: "Ilfov" },
    { value: 19, label: "Neamț" },
    { value: 20, label: "Cluj" },
    { value: 21, label: "Alba" },
    { value: 22, label: "Giurgiu" },
    { value: 23, label: "Argeș" },
    { value: 24, label: "Călărași" },
    { value: 25, label: "Bihor" },
    { value: 26, label: "Iași" },
    { value: 27, label: "Vâcea" },
    { value: 28, label: "Vrancea" },
    { value: 29, label: "Arad" },
    { value: 30, label: "Ialomița" },
    { value: 31, label: "Caraș-Severin" },
    { value: 32, label: "Galați" },
    { value: 33, label: "Gorj" },
    { value: 34, label: "Constanța" },
    { value: 35, label: "Satu Mare" },
    { value: 36, label: "Maramureș" },
    { value: 37, label: "Mehedinți" },
    { value: 38, label: "Sălaj" },
    { value: 39, label: "Vaslui" },
    { value: 40, label: "Mureș" },
    { value: 41, label: "Sibiu" },
    { value: 42, label: "Olt" }
  ],
