### ISSUE TITLE
Right hand column is not displayed on Family profile page

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#189]
The `Adauga-ti familia in cont` page is missing the right hand. columns as the other 2 tabs are displaying.

**Comment by cipick** [comment]
<img width="1188" alt="Screenshot 2020-04-13 at 10 21 21" src="https://user-images.githubusercontent.com/6429818/79101106-8c303480-7d70-11ea-80ba-ec845df41a71.png">
@RaduCStefanescu it seems that this page has the sidebar, it should be removed?

**Comment by RaduCStefanescu** [comment]
@cipick please checkout the latest code on `develop` branch, the sidebar is missing and it should be there.
<img width="1221" alt="Screenshot 2020-04-13 at 10 31 27" src="https://user-images.githubusercontent.com/15039873/79101809-0d3bfb80-7d72-11ea-8bdd-b8529e4e07a2.png">

**Comment by cipick** [comment]
🤦 yep i can see the changes now, will take this if that's ok

**Comment by surdu** [comment]
@cipick all yours
