### ISSUE TITLE
[Frontend] User creates profiles for people in his care

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#19]
As part of the platform, an user can insert details about people he has in his care to monitor them using his account.
![Adauga familia in cont](https://user-images.githubusercontent.com/15039873/77785254-965ded80-7064-11ea-9f8e-243c951189ed.png)
We will provide the API endpoints where this information needs to be POSTed.

**Comment by gabrielionita** [comment]
I'd like to take this issue
