### ISSUE TITLE
Load `Profilul meu` as default on homepage after login

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#197]
Currently, after login, no tab is being loaded on the homepage.
<img width="1219" alt="Screenshot 2020-04-13 at 10 36 14" src="https://user-images.githubusercontent.com/15039873/79102054-a3702180-7d72-11ea-94f7-86aceb2958e7.png">
The `Profilul meu` page should be loaded by default after the login.

**Comment by cipick** [comment]
i can take this one :)

**Comment by idormenco** [comment]
@cipick i know you took this one ,but i investigated also this issue .... 
I will leave here what changes should be done (in my opinion)
in App.js we should have this line 
`return <Redirect key={path} from={path} to="/account" />;`

**Comment by RaduCStefanescu** [comment]
@cipick @idormenco team work!
