### ISSUE TITLE
Fixes for `Profilul meu` page

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#199]
After a user completes his profile, we display a description of his profile in the `Profilul meu` page.

There are some issues that need to be fixed on that page:
- Change the `Izolare proprie la domiciliu:` from integer to string
- Display value for `Genul:`
- Display value for `Izolare alte persoane la domiciliu: `

**Comment by dragosrobertn** [comment]
Where do these values come from? Is there an endpoint response I can work with?

**Comment by RaduCStefanescu** [comment]
Yes, you should be able to GET these values from the `/api/profile` which is already covered. We just need to change the values retrieved from integer to string. These values are also present in frontend. Will come back on Slack with the information.

**Comment by idormenco** [comment]
@dragosrobertn can i have it ? i am new to ract and i already debugged this .

**Comment by dragosrobertn** [comment]
Good luck @idormenco! 👍
