### ISSUE TITLE
User completes an assessment for people in his care

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#20]
As part of the platform workflow, an user needs to complete an assessment for people in his care.

We need to integrate this component from the frontend components package.
code4romania/taskforce-fe-components#106

**Comment by RaduCStefanescu** [comment]
The linked issue in fe components is done: code4romania/taskforce-fe-components#106
The component is distributed as part of `V1.0.6` of the fe components.
We can now start working on this issue by including the newly developed component.

**Comment by mmircea16** [comment]
I can pick this issue. I would need to chat with someone about the backend integration

**Comment by surdu** [comment]
Please check with @oanamun if she already started working on this.

**Comment by oanamun** [comment]
@mmircea16  I can start working later today on it, but if you want to start sooner you can reassign it to you :)

**Comment by RaduCStefanescu** [comment]
Or, maybe you 2 @oanamun and @mmircea16 can collaborate :)

**Comment by RaduCStefanescu** [comment]
@oanamun we would like to continue this implementation in #124 
@mmircea16 has started working on it

**Comment by RaduCStefanescu** [comment]
This has been handled in #124 that we closed.
Closing this one as well.
