### ISSUE TITLE
[Frontend] User login page

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#21]
An user needs to be able to login to the platform.
![Log in](https://user-images.githubusercontent.com/15039873/77789196-40407880-706b-11ea-86dd-cbf20f22ff1b.png)

The authentication is handled by an Identity Server. The login page is displayed outside of the frontend application and will redirect back to it once the login is successful. We need to apply the styles from the mockup to this page: https://github.com/code4romania/stam-acasa/blob/develop/backend/src/StamAcasa.IdentityServer/Views/Account/Login.cshtml

**Comment by Dima000** [comment]
Salut, iau eu issue-ul

**Comment by RaduCStefanescu** [comment]
Please also involve @adascaliteiradu in this issue.
Thank you!
