### ISSUE TITLE
[Identity server] Use a certificate to sign access tokens

### ISSUE THREAD

**Issue by trupci** [code4romania/stam-acasa#214]
Identity Server signs access tokens with a key. For development scenarios, we are [currently](https://github.com/code4romania/stam-acasa/blob/97fc3bd30443cde13006b198e59df987d65658b8/backend/src/StamAcasa.IdentityServer/Startup.cs#L47) using `AddDeveloperSigningCredential`. For production, we should be using a certificate.

Reference [here](https://stackoverflow.com/questions/46142991/what-is-the-signing-credential-in-identityserver4)

**Comment by adrian-pistoleanu** [comment]
Nu ai nevoie de asa ceva. Nu am vazut certificat pe IdentityServer pt generat tokene. Faci asta decat daca esti speriat de bomba. Am implementat certificate in aplicatii distribuite IoT care erau deployed intr-o gramada de locatii ceea ce, evident, ridica probleme de securitate. Dar la un IS e indeajuns un KeyVault sau orice alta locatie de unde iti poti lua un key in mod aproape 100% sigur 
LE: + un admin care sa aiba habar de securitatea serverului pe care il administreaza.

**Comment by adrian-pistoleanu** [comment]
Ok, ma pot ocupa eu de asta, desi daca as avea task-ul asta la job, l-as rezolva rapid cu Azure Key Vault.
L-am gasit pe prietenul meu in IS, cu care o sa joc ping-pong cu certificate cu el diseara.
`AddSigningCredential(this IIdentityServerBuilder builder, X509Certificate2 certificate, string signingAlgorithm = "RS256");`
@RaduCStefanescu

**Comment by RaduCStefanescu** [comment]
Ok @adrian-pistoleanu e al tau
Ca sa iti mai dau cateva detalii - serviciile vor rula pe masini virtuale intr-un container Docker. As vrea sa putem sa citim certificatul de pe disk, si sa putem sa copiem certificatul in volumul imaginii de Docker. Sa imi zici cum ti se pare ideea.

**Comment by adrian-pistoleanu** [comment]
Da, certificatul va fi citit de pe disk. Docker e un pic in afara stack-ului meu, noi dăm deploy direct din VS in Azure sau, mai rar, intr-un IIS box local. Oricum, ma uit si la acest aspect.

**Comment by adrian-pistoleanu** [comment]
Folosesc un certificat incarcat de pe disk si totul functioneaza cum trb cu acest certificat. Chestia e ca il preiau folosind o parola(adica tot nu e suficient de sigur). In Windows de obicei pt asta se foloseste Certificate Store(si astfel scapi de parola certificatului in aplicatie).  O sa vad cum pot incarca certificatul in Docker.

Un alt aspect(posibil issue) pe care l-am descoperit este ca ca in acest IdentityServer nu functioneaza https-ul (https://localhost:5000 e mort). Chestia e ca imediat ce schimbi environmentul din Development pe Production isi da switch pe https, care nu functioneaza. Pe production, prin https incearca sa ia tokenele. 
In cazul nostru API serverul foloseste numai http sa preia token de la IdentityServer (le ia numai prin http://localhost:5001 - aici securitatea e discutabila, e posibil sa fie safe enough daca securitatea serverului e buna. Oricum, complet safe nu este in configuratia actuala). @RaduCStefanescu

**Comment by adrian-pistoleanu** [comment]
Scenariul la care ma gandesc eu(cred improbabil), cine are acces pe server(unde sa zicem ca sunt gazduite ambele API si IdentityServer) poate sniffui tokenele/mesajele care se transmit prin http://localhost:5001 si poate impersona userul(asta cu tot cu certificat SSL). Nu sunt expert pe retelistica si securitate pe porturi si ip-uri dar cred ca se pot intercepta lejer mesajele transmise pe http.

**Comment by catileptic** [comment]
@adrian-pistoleanu - can you please submit a Pull Request with your implementation? We'd like to ship the MVP of this app. :)

**Comment by adrian-pistoleanu** [comment]
Vad ca exista deja un update cu o implementare asemanatoare. Se poate inchide.
