### ISSUE TITLE
Profilul meu page does not work as expected

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#226]
After login, the `Profilul meu` page does not load the profile page structure.

<img width="1304" alt="Screenshot 2020-04-15 at 20 21 46" src="https://user-images.githubusercontent.com/15039873/79367691-f5719c80-7f56-11ea-985d-43bbc7a537de.png">

After reloading the page, the form is loaded, but the links bar on the right hand side is loaded twice.

<img width="1313" alt="Screenshot 2020-04-15 at 20 23 41" src="https://user-images.githubusercontent.com/15039873/79367811-1df99680-7f57-11ea-985b-a8a2b1529ebe.png">

**Comment by teodoradima** [comment]
🙋‍♀️
