### ISSUE TITLE
`Profilul meu` content not loaded by default after redirect

### ISSUE THREAD

**Issue by aniri** [code4romania/stam-acasa#236]
- I filled in the evaluation form for the first time
- after saving the form, I got redirected, but no content was opened by default, see screenshot:

![Screenshot from 2020-04-16 17-00-21](https://user-images.githubusercontent.com/1358055/79466069-c0bc1e80-8004-11ea-950a-df4b5a4c8587.png)

**Comment by teodoradima** [comment]
🙋‍♀️

**Comment by RaduCStefanescu** [comment]
Fixed in #241
