### ISSUE TITLE
Forgot password option not working

### ISSUE THREAD

**Issue by aniri** [code4romania/stam-acasa#237]

**Comment by irinel-nistor** [comment]
I'd like to work on this one

**Comment by RaduCStefanescu** [comment]
It's all yours @irinel-nistor 
As far as I remember, this was not implemented yet, so it is a new feature.

**Comment by irinel-nistor** [comment]
I have a couple of questions:
1. Should this use the same queues mechanism as register to send the email
2. Should I create an Email template similar to register for this?

**Comment by RaduCStefanescu** [comment]
1. yes
2. yes
