### ISSUE TITLE
Create red flags in the last 24h component

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#24]
**Prototype**
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=144%3A10

**Design**
<img width="249" alt="Screenshot 2020-03-26 at 23 49 49" src="https://user-images.githubusercontent.com/11520795/77700265-81c61a80-6fbc-11ea-82f7-6cc7649625b6.png">

**Comment by Patricia008** [comment]
Salut. Fac eu componenta :)

**Comment by surdu** [comment]
We try to use Elasticsearch to display the info that this component should display. We leave this open until that effort succeeds, so please don't work on this yet.

**Comment by Patricia008** [comment]
Awesome, but it's already done.

**Comment by surdu** [comment]
Closed in #93
