### ISSUE TITLE
Unregistered users are not correctly redirected to the home page when accessing the app using a protected route

### ISSUE THREAD

**Issue by teodoradima** [code4romania/stam-acasa#242]
**Steps to reproduce:**
GIVEN
- User is logged out of the application;

WHEN
- User attempts navigation using the account protected route (https://dev.stamacasa.ro/account/ );

THEN
- User is presented with a static blank screen with no elements at all.

Note: For `/add-members` and `/evaluation` routes, the user is presented with the home page but the url does not change to `/`.

**Expected result:**
User should be redirected to the homepage and the url in the address bar should default to `/`.

**Comment by RaduCStefanescu** [comment]
Good catch @teodoradima !

**Comment by teodoradima** [comment]
🙋‍♀️
