### ISSUE TITLE
Send daily assessment emails only to parent users

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#246]
Currently, when we send daily assessment email, we query for all users and send email to them. The emails should be sent only for parent users, the ones that created the account.

The change should happen in `AssessmentNotificationsDispatch:Process()`

**Comment by mihaipopescu** [comment]
Sounds simple enough, I'll take a look.

**Comment by RaduCStefanescu** [comment]
All yours @mihaipopescu 
Let us know if you have any questions 👍

**Comment by mihaipopescu** [comment]
I'm still trying to figure out how would I go about and test this in general as I don't have an SMTP server running. Would also be nice to have a way to poke around the database as I enter some data as I just discovered Alice and Bob users.

**Comment by RaduCStefanescu** [comment]
Are you not able to start your development environment using docker files?

**Comment by RaduCStefanescu** [comment]
Closed by #291
