### ISSUE TITLE
Content for About page

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#247]
Please provide content for About page on Stam Acasa.

**Comment by overeha** [comment]
About page and logos below

Despre proiect

Ești izolat la domiciliu iar telefoanele de urgență sunt împovărate de numărul mare de apeluri, făcând astfel evaluarea situațiilor medicale la nivel național o problemă reală. Oare câți alții ca tine sunt în situația ta?

Stăm Acasă este o soluție digitală cu ajutorul căreia reducem suprasolicitarea numerelor de urgență, colectăm rapid informații de la o populație foarte mare și vom facilita astfel o evaluare constantă oferind sprijin în managementul cazurilor pentru autorități.

Stăm Acasă este un proiect dezvoltat în parteneriat cu Guvernul României prin Autoritatea pentru Digitalizarea României, cu colaborarea Ministerului Sănătății, de către organizația Code for Romania, în cadrul programului Code for Romania Task Force. 

[logo Guvern + ADR] [logo Code for Romania]

Programul Code for Romania Task Force este susținut de: 
[logo ING] [logo RAF] [logo FVR]

![banda sponsori](https://user-images.githubusercontent.com/45068169/79752960-c7f16e00-831d-11ea-92a8-65422100fb4d.png)

![Sigla ADR_new](https://user-images.githubusercontent.com/45068169/79753016-e9eaf080-831d-11ea-924d-8602b5569956.jpg)
![logo Code for Romania](https://user-images.githubusercontent.com/45068169/79753023-ebb4b400-831d-11ea-9cf6-07fd45fe07a6.png)

**Comment by RaduCStefanescu** [comment]
Thank you @overeha This one is good to go it seems
