### ISSUE TITLE
Incorrect timing of question inside the form

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/stam-acasa#249]
If the user answers with 'No' to the following question:
"Ai avut in ultimele 14 zile orice semn/simptom de raceală sau gripă?"
The next question the user gets is:
"Te rugăm să specifici zona/țara la care te referi"

This does not make sense at this moment as there has not been a prior question to ask if the user has traveled to any foreign countries.

The exact flow followed was:
1. Age: 120
2. Gendre: male
3. Disease: heart, diabetes, lungs
4. Ai avut in ultimele 14 zile orice semn/simptom de raceală sau gripă? 'No'
5. Te rugăm să specifici zona/țara la care te referi

Also, going forward with the form on the 'No symptoms' path, the user still gets the following questions:
- Gândindu-te la perioada de 14 zile înainte de a avea primul simptom/semn de răceală sau gripă: Ai fost la un spital sau în incinta oricărui alt serviciu medical?
- Gândindu-te la perioada de 14 zile înainte de a avea primul simptom/semn de răceală sau gripă: Ai fost în contact direct cu o persoană diagnosticată/ confirmată cu noul coronavirus?

**Comment by irinel-nistor** [comment]
This question appears to have been removed from the new user or follow up forms. In this case, is this still an issue @RaduCStefanescu ?
![image](https://user-images.githubusercontent.com/8067395/80283502-b0045a80-8720-11ea-8995-cd76ee573b08.png)

**Comment by RaduCStefanescu** [comment]
No, we can close this one.
Thank you @gepaltineanu and @irinel-nistor
