### ISSUE TITLE
Number of users logged in 

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#25]
**Prototype**
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=144%3A10

**Design**
<img width="310" alt="Screenshot 2020-03-26 at 23 51 03" src="https://user-images.githubusercontent.com/11520795/77700363-b639d680-6fbc-11ea-944e-45460312103b.png">

**Comment by chedydy** [comment]
Buna, il iau eu.

**Comment by bianca-gauca** [comment]
Is it still available? I want to work on it.

**Comment by Patricia008** [comment]
I am currently working on https://github.com/code4romania/stam-acasa/issues/24 which is the same component, different props

**Comment by surdu** [comment]
We try to use Elasticsearch to display the info that this component should display. We leave this open until that effort succeeds, so please don't work on this yet.

**Comment by surdu** [comment]
Closed in #93
