### ISSUE TITLE
Missing role link for https://www.aadr.ro

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#251]
Starting point: https://dev.stamacasa.ro

**Expected:**
Click on role img Autoritatea pentru digitalizarea României
Autoritatea pentru digitalizarea României site opens https://www.aadr.ro

**Actual**:
Click on role img Autoritatea pentru digitalizarea României
Guvernul României site opens https://www.gov.ro

![Screenshot 2020-04-18 at 12 26 08](https://user-images.githubusercontent.com/61550276/79650539-cc047b00-81b9-11ea-8cbc-534fe585c5c7.png)

**Comment by RaduCStefanescu** [comment]
@overeha where should the ADR logo link to? The ADR site or the gov site?

**Comment by surdu** [comment]
We might want to modify the URL also/only in the taskforce components.

**Comment by RaduCStefanescu** [comment]
Yes, because we have different behaviors on some projects.

**Comment by RaduCStefanescu** [comment]
We decided internally that the link will be to the gov.ro site, as it is now
Thank you for your help @DragomirStefanaCatalina
