### ISSUE TITLE
Search bar doesn't work

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#252]
Starting point: https://dev.stamacasa.ro

**Actual**:
Search bar doesn't show any result

![Screenshot 2020-04-18 at 12 26 33](https://user-images.githubusercontent.com/61550276/79651957-35848980-81ba-11ea-8afe-06df9e658ad7.png)

**Comment by RaduCStefanescu** [comment]
Yup, you are right. In the context of this site, the search bar has no sense and it should be removed.

**Comment by idormenco** [comment]
will do
