### ISSUE TITLE
Cant go back to stamacasa from cetrebuiesafac

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#253]
Starting point: https://dev.stamacasa.ro

**Expected**:
1. Click on 

> Ce ma fac

from the bottom of the page
![Screenshot 2020-04-18 at 12 26 49](https://user-images.githubusercontent.com/61550276/79654601-fc004e00-81ba-11ea-894c-41f9ab550476.png)

2. Page https://cetrebuiesafac.ro opens

3. Click on back 

4. Return to https://dev.stamacasa.ro

**Actual**:
1. Click on 

> Ce ma fac

from the bottom of the page

2. Page https://cetrebuiesafac.ro opens

3. Click on back 

4. https://cetrebuiesafac.ro loads 

5. Întrebări frecvente from https://cetrebuiesafac.ro appears 

![Screenshot 2020-04-18 at 21 27 38](https://user-images.githubusercontent.com/61550276/79656339-7c26b380-81bb-11ea-9c25-0cb1a1bcf426.png)

**Mentions** 
If

> Date la zi
> Diaspora Hub
> Ro Help
> Știri Oficiale

are accessed, the pages open & you can go back to https://dev.stamacasa.ro

**Comment by surdu** [comment]
Maybe I'm misunderstanding this, but it sounds to me like this is a missing link issue with https://github.com/code4romania/ce-ma-fac

**Comment by RaduCStefanescu** [comment]
No, the issue is with the link we are using for Ce ma fac in the footer. The correct link should be cetrebuiesafac.ro and the text changed to Ce trebuie sa fac. Because of the redirect from cemafac.ro to cetrebuiesafac.ro, we are getting this behavior.

**Comment by idormenco** [comment]
will do
