### ISSUE TITLE
Blank page after confirmation message for new account 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#254]
Starting point: https://dev-is.stamacasa.ro/Identity/Account/ConfirmEmail?userId=19cedc5d-f3ab-461e-a727-cf4a99fd2873&code=Q2ZESjhCbmwvckZidU01RGxXUVowenJhbUVxNU1abmw3cmovQWozUWN6UmZiVCs0U2U1ejFZVUlONHdYVFltYXZtRjlJakhZYWVmREtJcEhmMmlrOWVybDlKaENZRG5RRTVUVEJ0cjJTekErcnNma0dmd1ovRXFnKytIVWJtcEZKRzZrUk5pS1dlcTZ0QU1UcExWajVYeXpoeU1ZVHNFMy9jNTZmRmkxUW9FVWFVcVp2TVZLY0JaUUtucnFwTWVXMmR6dUNTWWpyNkFMVzEwWm56U3oxak5HTkRJMHo5eUUxNHlhM0pWeTIwd3FzOEdyUkUxRlBIY0FLaDQydi9BWE9Nc21vZz09&returnUrl=https%3A%2F%2Fdev.stamacasa.ro%2Fregister-complete

**Expected**:
After confirmation message appears 
![Screenshot 2020-04-18 at 12 27 53](https://user-images.githubusercontent.com/61550276/79660337-a75dd280-81bc-11ea-96b3-fda5de202276.png)
Page https://dev.stamacasa.ro
or
https://dev.stamacasa.ro/account
loads & appears 

**Actual**:

Confirmation message appears 

Page https://dev.stamacasa.ro/account loads & appears as a blank page
![Screenshot 2020-04-18 at 12 28 10](https://user-images.githubusercontent.com/61550276/79660565-b8a6df00-81bc-11ea-86d8-1779627cb470.png)

**Comment by teodoradima** [comment]
🙋‍♀️

**Comment by RaduCStefanescu** [comment]
This is handled as part of #285
