### ISSUE TITLE
Cant edit your profile 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#255]
Starting point: https://dev.stamacasa.ro/account/me

**Expected**:

Editing your profile by clicking 

> Editare profil

**Actual**:

Click on 

> Editare profil

![Screenshot 2020-04-18 at 12 32 59](https://user-images.githubusercontent.com/61550276/79664108-bc873100-81bd-11ea-8e8c-a6921438b8a4.png)

Nothing happens

**Comment by RaduCStefanescu** [comment]
This is also being handled as part of #287

**Comment by RaduCStefanescu** [comment]
Fixed in #287
