### ISSUE TITLE
Name field containing characters doesn't appear mandatory 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#256]
Starting point: https://dev.stamacasa.ro/account/me

**Expected**:
Name field containing characters should be mandatory when you add Alte persoane

**Actual**:
You can click on

> Continuă

![Screenshot 2020-04-18 at 12 36 18](https://user-images.githubusercontent.com/61550276/79667942-d1b08f80-81be-11ea-82e3-9bf3a29d3ac5.png)
 & continue the procedure to add Alte persoane when Name field consists of symbols, not characters

**Comment by cipick** [comment]
i can take this one

**Comment by RaduCStefanescu** [comment]
All your @cipick

**Comment by RaduCStefanescu** [comment]
Fixed by #338
