### ISSUE TITLE
Cant add a family member with Phone number field empty 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#257]
Starting point: https://dev.stamacasa.ro/account/me

**Expected**:
You are permitted to add a family member even if the person doesn't have a phone number 

**Actual**:
You cant click on

> Continua

in order to add a family member if the Phone number field is empty
![Screenshot 2020-04-18 at 12 37 17](https://user-images.githubusercontent.com/61550276/79668902-a9299500-81c0-11ea-989e-a9b6856ecd2c.png)

**Comment by RaduCStefanescu** [comment]
@overeha should we make telephone number on add family member mandatory?

**Comment by overeha** [comment]
No, it should not be mandatory. You may add kids under 10 here who do not have phone numbers or ppl in poor communities who do not have phones.

**Comment by RaduCStefanescu** [comment]
Ok, so the telephone number field is not mandatory on family profile. Thank you!
