### ISSUE TITLE
History doesn't correspond 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#258]
Starting point: https://dev.stamacasa.ro/account/me

**Expected**:
Each profile should have customised history 

**Actual**:
My history doesn't correspond to my profile
![Screenshot 2020-04-18 at 12 42 28](https://user-images.githubusercontent.com/61550276/79668982-23f2b000-81c1-11ea-8179-6e52637e5d79.png)

**Comment by RaduCStefanescu** [comment]
Yup, currently the load history feature is not working properly. Starting from this issue and after updating the form used for assessments, the assessment history will load correctly.

**Comment by RaduCStefanescu** [comment]
Just an update on my side - we have updated the form to the correct version, containing the correct questions. The format of the answers in the backend has changed and this should be the correct format that we need to handle on the historic component.

**Comment by mmircea16** [comment]
If this is ready to be picked up frontend-wise, I can work on it

**Comment by RaduCStefanescu** [comment]
Yes please, this one is really important. I will give you more details on Slack 👍
