### ISSUE TITLE
Number of filled in forms component

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#26]
**Prototype**
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=144%3A10

**Design**
<img width="306" alt="Screenshot 2020-03-26 at 23 51 16" src="https://user-images.githubusercontent.com/11520795/77700404-cc479700-6fbc-11ea-8dc9-aa716e7d4aee.png">

**Comment by cimpoesub** [comment]
Salut. Pot sa ma ocup eu de asta.

**Comment by danmana** [comment]
Same component as #24 , just different props

**Comment by surdu** [comment]
We try to use Elasticsearch to display the info that this component should display. We leave this open until that effort succeeds.

**Comment by surdu** [comment]
Closed in #93
