### ISSUE TITLE
Cant edit your family member's profile

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#260]
Starting point: https://dev.stamacasa.ro/evaluation/other-members/11

**Expected**:

Editing your family member's profile by clicking

> Editare profil

**Actual**:

Click on

> Editare profil

Nothing happens

**Comment by irinel-nistor** [comment]
I"d like to work on this one

**Comment by RaduCStefanescu** [comment]
Hey @irinel-nistor all yours!

**Comment by irinel-nistor** [comment]
None of the edit profile buttons seem to do anything. Would this be a new feature? Should the button click take the user back to the form where he can submit the data again?

**Comment by RaduCStefanescu** [comment]
Yes, we should re-use the form for creating the profile, but in this case, we need to pre-populate the form with the details the user already inserted. Do you think this is doable?

**Comment by irinel-nistor** [comment]
Yes, that's what I had in mind. Should I also create a PUT profile endpoint? We currently only have on for family.

**Comment by RaduCStefanescu** [comment]
Yes, we need to implement the UPDATE operation as well.
