### ISSUE TITLE
Phone number field containing numeric doesn't appear mandatory

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#261]
Starting point: https://dev.stamacasa.ro/account/me

Expected:
Phone number field containing numeric should be mandatory when you fill in Date Personale/Profilul Meu.

Actual:
You can click on Continua button.
![numeric phone number](https://user-images.githubusercontent.com/47795680/79670891-666abb80-81c6-11ea-9df7-3f04ea95fcf7.png)

**Comment by Dima000** [comment]
I would like to take this one.
And also https://github.com/code4romania/stam-acasa/issues/263, because they seem related

**Comment by RaduCStefanescu** [comment]
Fixed by #277
