### ISSUE TITLE
Hover message in english

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#262]
Starting point: https://dev.stamacasa.ro/account

Expected: Hover message should be written in romanian.

Actual: Hover message is write in english.

![hover in english](https://user-images.githubusercontent.com/47795680/79671871-ef392580-81cd-11ea-9c89-ab9840e5338b.png)

**Comment by surdu** [comment]
For whom will tackle this issue, [this](https://stackoverflow.com/questions/5272433/html5-form-required-attribute-set-custom-validation-message) might be a good starting point.

**Comment by tudorgergely** [comment]
FYI: the language used in form validation messages is the default language of your OS (not sure if we should force Romanian or not) @surdu

**Comment by surdu** [comment]
Since we don't offer other language on the website, and most/all users of this website will be Romanian speaking persons, I propose that we force it to Romanian for now. When we'll have multiple languages, we'll let the language selection mechanism choose the language of these messages.

**Comment by irinel-nistor** [comment]
> For whom will tackle this issue, [this](https://stackoverflow.com/questions/5272433/html5-form-required-attribute-set-custom-validation-message) might be a good starting point.

We use this [input]( https://taskforce-fe-components.now.sh/?path=/docs/input--types). I tried to apply the suggested solution on the component but it didn't work. It probably needs work in the components library, right?

**Comment by surdu** [comment]
@irinel-nistor Yes. You'll either have to target the input from inside the component or better yet modify the base component so when it is required changes the required validation message.

**Comment by irinel-nistor** [comment]
I'd like to work on this issue

**Comment by surdu** [comment]
@irinel-nistor all yours 🚀
