### ISSUE TITLE
No character number limit on phone field

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#263]
Starting point: https://dev.stamacasa.ro/account

Expected: you should fill in with max 13 - min 10 numeric characters.

Actual: no limit of character number.

![no character limit](https://user-images.githubusercontent.com/47795680/79672249-830bf100-81d0-11ea-931d-c3493fdd5413.png)

**Comment by Dima000** [comment]
I would like to take this one.
And also https://github.com/code4romania/stam-acasa/issues/261, because they seem related
