### ISSUE TITLE
Modify excel file sent to authorities 

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#265]
The excel file sent to authorities contains answers in int format, for questions that have multiple answers, just as we are sending these responses from frontend, i.e. 
`questionText1`:`Ai avut vreunul din simptomele de mai jos?` 
`answer1`: `0`
Instead of sending ids, we need to map the answers from the assessment files `formNewUser.json` and `formFollowUp.json`.

**Comment by idormenco** [comment]
will do
