### ISSUE TITLE
'Varsta in ani impliniti' should be grater than 18

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#273]
Starting point: https://dev.stamacasa.ro/account

Expected: When you create your account you should select only numbers grater than 18 when you fill-in 'Varsta in ani impliniti'.

Actual: You can type any number between 0 and 120. 

![Varsta0](https://user-images.githubusercontent.com/47795680/79748910-81484780-830e-11ea-9600-89b6ddf60b7f.png)

**Comment by surdu** [comment]
I don't think this is a requirement, right @RaduCStefanescu ?

**Comment by RaduCStefanescu** [comment]
From my point of view, yes, it is.

**Comment by RaduCStefanescu** [comment]
@overeha what is your opinion?

**Comment by overeha** [comment]
I think it should be 18 and above for the main account as you have to be able to consent to terms of use. 
However, it should not be mandatory for the associated family members profiles. You may add your kid who is under 10 or so so you can monitor it.

**Comment by overeha** [comment]
Currently checking with our lawyer.

**Comment by overeha** [comment]
Yes, 18 ani impliniti. 
I confirm the lawyer says that the main user should be at least 18.

**Comment by andorremus** [comment]
Should it have a bespoke validation message or just the usual html field validation will do?
E.g number should be larger than x! / the main account holder should be at least 18 years old

**Comment by RaduCStefanescu** [comment]
We should have the message in Romanian - Trebuie sa ai minim 18 ani împliniți pentru a-ți crea cont in platformă!

**Comment by andorremus** [comment]
Ok, and only when filling the form for him/herself, the main account holder.

**Comment by RaduCStefanescu** [comment]
Yup - dependents can be underaged, that's the whole point actually 😃

**Comment by andorremus** [comment]
Assign this to me please

**Comment by RaduCStefanescu** [comment]
All yours @andorremus

**Comment by andorremus** [comment]
I tried to look in the repo for ways to handle input validation errors and the only other way is the html5 validation which doesn't work with safari, can you guide me towards an example ?

**Comment by surdu** [comment]
@andorremus [This recent PR](https://github.com/code4romania/taskforce-fe-components/pull/166) for our shared components might be of help to you. Especially, the [examples in the storybook](https://github.com/code4romania/taskforce-fe-components/pull/166/files#diff-c3fc3ab0b3c203909997af814385a04b).

**Comment by andorremus** [comment]
It does indeed, thank you very much. @surdu
