### ISSUE TITLE
'Formularul tau' some fields should be mandatory

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#275]
Starting point: https://dev.stamacasa.ro/evaluation/me
Select 'Da' on 'Alte simptome';
Click 'Inainte' button;
Click 'Inainte' without filling in the field.

Expected: When you check others symptoms, you should not be able to click on 'Inainte' button if the field is empty.

Actual: You can click on 'Inainte' button even if the the field is empty.

![mandatory field](https://user-images.githubusercontent.com/47795680/79753679-9a54f680-8316-11ea-80f9-919ea4b42340.png)

**Comment by aniri** [comment]
I think this is also fixed, same as https://github.com/code4romania/stam-acasa/issues/313
