### ISSUE TITLE
When 'Niciuna de mai sus' is selected, you can still select other option.

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#279]
https://dev.stamacasa.ro/add-member
Go to 'Date despre starea lor de sanatate';
Go to 'I-a spus vreun medic că are oricare dintre următoarele afecțiuni?';
Select 'Niciuna de mai sus';
Select any others options;

Expected: When 'Niciuna de mai sus' is selected, you should not be able to select other option.

Actual: Even if the 'Niciuna de mai sus' button is selected, you can still select other options.

![multiple selection allowed](https://user-images.githubusercontent.com/47795680/79768937-bfa02f80-832b-11ea-9be1-71782cfad879.png)

**Comment by cipick** [comment]
i can take this
