### ISSUE TITLE
Generate link for login and redirect in daily assessment email

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#280]
When we send the daily assessments email, we need to send a link to the login form and then redirect the user to the `/evaluation/me` route. 
The base URL needs to be taken from config, and the URL needs to be published in the email that is sent to the users.

**Comment by irinel-nistor** [comment]
I would like to work on it

**Comment by RaduCStefanescu** [comment]
All yours @irinel-nistor
