### ISSUE TITLE
User is able to see only first family member registered 

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#281]
Starting point: https://dev.stamacasa.ro/account/other-members/
Go to drop down and select another family member;

Expected: User should be able to see the selected family member profile.

Actual: When user select another family member from the drop down, the profile is not changed. User can see all the time only first family member profile.

![family members drop down](https://user-images.githubusercontent.com/47795680/79774592-47d60300-8333-11ea-98c6-0a6dd7ca60de.png)

**Comment by teodoradima** [comment]
🙋‍♀️

**Comment by RaduCStefanescu** [comment]
All yours @teodoradima !

**Comment by teodoradima** [comment]
Also fixes #282
