### ISSUE TITLE
User is not able to change family members profiles from the link.

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#282]
Starting point: https://dev.stamacasa.ro/account/other-members/
Go to 'Alte persoane in grija' link;
Click on another family member profile.

Expected: Family member profile should be changed.

Actual: When user click on another family member link, nothing happened, profile is not changed.

![family members link](https://user-images.githubusercontent.com/47795680/79776213-b4ea9800-8335-11ea-941b-5ae7b9229525.png)

**Comment by teodoradima** [comment]
Fixed in scope of #281

**Comment by RaduCStefanescu** [comment]
This is fixed as part of #281
