### ISSUE TITLE
No 'Edit profile' button on family members profile.

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#284]
Starting point: https://dev.stamacasa.ro/account/other-members/

Exxpected: On family members profile should exist an 'Edit profile' button.

Actual: 'Edit profile' button does not exist.

![Edit profile button](https://user-images.githubusercontent.com/47795680/79781647-131b7900-833e-11ea-9f9a-38d660918d05.png)

**Comment by irinel-nistor** [comment]
I added it as part of this changes https://github.com/code4romania/stam-acasa/pull/287

**Comment by RaduCStefanescu** [comment]
This one is fixed in #287
