### ISSUE TITLE
When the user selects 'Nici una de mai sus' on 'Afectiuni agravante' message displayed on his profile should be 'Nu exista'

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#296]
Starting point: https://dev.stamacasa.ro/account/me

Expected: When the user selects 'Nici una de mai sus' on 'Afectiuni agravante' message displayed on his profile should be 'Nu exista' or something like this.

Actual: When the user selects 'Nici una de mai sus' on 'Afectiuni agravante' message displayed on his profile is 'Nici una de mai sus'.

![afectiuni agravante](https://user-images.githubusercontent.com/47795680/79887609-73bcbb80-83fb-11ea-8ecb-789fe00ed255.png)

**Comment by idormenco** [comment]
on it
