### ISSUE TITLE
Confusing redirect after adding family member

### ISSUE THREAD

**Issue by aniri** [code4romania/stam-acasa#299]
Current behaviour:
- go to `https://dev.stamacasa.ro/add-member`
- add new family member details
- save info and get redirected to `https://dev.stamacasa.ro/account/me`

Expected behaviour;
- go to `https://dev.stamacasa.ro/add-member`
- add new family member details
- save info and get redirected to `https://dev.stamacasa.ro/account/other-members/`

**Comment by RaduCStefanescu** [comment]
Fixed by #331
