### ISSUE TITLE
Misleading loading message for other members profile

### ISSUE THREAD

**Issue by teodoradima** [code4romania/stam-acasa#302]
**Steps to reproduce**
GIVEN
- User is logged in and has at least one family member with a profile created

WHEN
- User navigates to "Alte persoane" tab

THEN
- User is presented with the "Nu exista membri" message while the data is loading

**Expected behavior**
- User should be presented with the "Datele se incarca" message while the data is loading

Note: This is impacting users that run the app on slow networks.

**Comment by aniri** [comment]
I can't seem to reproduce this in https://dev.stamacasa.ro/

**Comment by mmircea16** [comment]
I managed to reproduce it by tweaking the network speed in the developer tools to "Slow 3G". I have a fix for it - I will create a PR for it
