### ISSUE TITLE
Clicking on a Alte persoane în grijă option does not redirect to selected person details

### ISSUE THREAD

**Issue by aniri** [code4romania/stam-acasa#303]
Current behaviour:
- add at least two `alte persoane` profiles
- go to my account
- see profile details & `Alte persoane în grijă:`
- click on the second person from the links
- you are redirected to `Alte persoane` / `https://dev.stamacasa.ro/account/other-members`
- the first person from the list is selected in the dropdown and details for that person are shown in profile box

Expected behaviour:
- add at least two `alte persoane` profiles
- go to my account
- see profile details & `Alte persoane în grijă:`
- click on the second person from the links
- you are redirected to `Alte persoane` / `https://dev.stamacasa.ro/account/other-members`
- **the second person (=the one we selected) from the list is selected in the dropdown and details for that person are shown in profile box**

**Comment by teodoradima** [comment]
Duplicate of #282 ? Not aware if the fix was deployed on the test env yet. 🤔

**Comment by RaduCStefanescu** [comment]
The fixes are merged, but we did not make a new deployment.

**Comment by aniri** [comment]
closing this then :)
