### ISSUE TITLE
Useless whitespace on "Profilul meu" page

### ISSUE THREAD

**Issue by teodoradima** [code4romania/stam-acasa#304]
**Platform**: Mobile, Safari browser

There's some whitespace breaking the app flow on "Profilul meu" page (self or other member).

![image](https://user-images.githubusercontent.com/9938889/79909494-be532d80-8425-11ea-9f00-f19f9d346bf2.png)

**Comment by mihainsto** [comment]
I can take this.

**Comment by surdu** [comment]
Fixed in #356
