### ISSUE TITLE
Sometimes when user expands hamburger menu and attempts navigation to another tab, both previous and newly selected tabs are highlighted

### ISSUE THREAD

**Issue by teodoradima** [code4romania/stam-acasa#306]
**Platform**: Mobile, Safari browser

Sometimes when user expands hamburger menu and attempts navigation to another tab, both previous and newly selected tabs are highlighted. However, new tab content is rendered successfully.

![image](https://user-images.githubusercontent.com/9938889/79910403-51d92e00-8427-11ea-9d80-11e5b6a12666.png)

**Comment by surdu** [comment]
Couldn't reproduce on web and android 😞

**Comment by teodoradima** [comment]
I can't reproduce it anymore on iOS as well. I guess we can close it?

**Comment by aniri** [comment]
closing this for now as it can't be reproduced. maybe it was fixed indirectly :/
