### ISSUE TITLE
Missing daily reminder email for assessment form

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#310]
**Expected**:
Daily reminder email for assessment form
![Screenshot 2020-04-22 at 11 42 13](https://user-images.githubusercontent.com/61550276/79961067-da3ee980-848e-11ea-88e1-0680ff930813.png)

**Actual**:
5 days old profile & not even one daily reminder email for assessment form

**Comment by RaduCStefanescu** [comment]
I will look into the Scheduling service in an hour and I will let you know if this is a bug or a misconfiguration on our side. Nice attention to details! 💯
