### ISSUE TITLE
Missing field to be completed when the user is in a different situation for 2 questions

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#314]
Starting point: https://dev.stamacasa.ro/evaluation/me

**Expected**:
Field to be completed when the user is in a different situation than those stated before

For example:
![Screenshot 2020-04-22 at 12 11 50](https://user-images.githubusercontent.com/61550276/79963978-b8476600-8492-11ea-9c71-55fa78d71721.png)

**Actual**:

Missing field to be completed when the user is in a different situation than those stated before
The user can go forward without having the opportunity to type anything about 

> Alta situatie

![Screenshot 2020-04-22 at 11 33 43](https://user-images.githubusercontent.com/61550276/79963644-538c0b80-8492-11ea-943f-7aa861f9b694.png)

![Screenshot 2020-04-22 at 11 34 24](https://user-images.githubusercontent.com/61550276/79963660-58e95600-8492-11ea-81dc-4eb055638f58.png)

**Comment by mmircea16** [comment]
For this one we can do one of 2 options:

- have another optional question immediately after
- use `type: "OTHER"` on the "Alta situatie" option - this will add an inline text input in the question

For either choice the change is only in the json of the form - no js code needed.

**Comment by aniri** [comment]
@mmircea16 I think we can use the same option as for the `Alte simptome:` question to be consistent :smile:

**Comment by catileptic** [comment]
We decided this is no longer an Issue since the current stay-at-home situation will soon come to an end.
