### ISSUE TITLE
Misleading "Reincepe testul" button's position

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#316]
Starting point: https://dev.stamacasa.ro/evaluation/me

**Actual**:
The user may make an unintentional mistake by clicking on
> Reincepe testul

instead of 

> Inainte

The

> Reincepe testul

 button's position may be misleading.

![Screenshot 2020-04-22 at 12 26 05](https://user-images.githubusercontent.com/61550276/79965711-09f0f000-8495-11ea-9cb6-9ad9b518c634.png)

![Screenshot 2020-04-22 at 12 26 32](https://user-images.githubusercontent.com/61550276/79965721-0eb5a400-8495-11ea-935b-6b20f20b95fc.png)

**Comment by bvizureanu** [comment]
@overeha @andrabrinzaniuc @stefin your input would be of many helpz :D

**Comment by bvizureanu** [comment]
This might be transfered to the frontend components repo
