### ISSUE TITLE
Missing lef & right padding for "developed by" header

### ISSUE THREAD

**Issue by aniri** [code4romania/stam-acasa#327]
Developed by header should have a small padding on mobile devices.

![Screenshot_20200422-202018_Chrome](https://user-images.githubusercontent.com/1358055/80013456-96240700-84d7-11ea-8576-d0b543d2e6b6.jpg)

**Comment by surdu** [comment]
@aniri Do we want this only on StamAcasa or everywhere else? If everywhere else, we might want to move this on the taskforce components repo

**Comment by aniri** [comment]
> @aniri Do we want this only on StamAcasa or everywhere else? If everywhere else, we might want to move this on the taskforce components repo

@surdu I think it will be easier to keep the specific styling details in the project repo and not in the components. The component could be used in a different layout in other projects and also the number of logos displayed are different between projects.

They just need a small left/right padding or margin here :smiley:

**Comment by aniri** [comment]
closing this as it was fixed in #366
