### ISSUE TITLE
7 daily reminder emails for assessment form in one day 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#346]
**Expected**:
1/2 daily reminder email/s for assessment form

**Actual**:
7 daily reminder emails for assessment form in one day 
![Screenshot 2020-04-23 at 21 04 21](https://user-images.githubusercontent.com/61550276/80133547-1022c180-85a6-11ea-9d40-623be9515809.png)

**Comment by RaduCStefanescu** [comment]
Hi @DragomirStefanaCatalina 
Yes, I did some testing today, sorry for spamming you with emails.
Will keep this bug open just in case.

**Comment by catileptic** [comment]
This is no longer reproducing. Closing this.
