### ISSUE TITLE
Future dates can be selected from calendar

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#348]
Starting point: https://dev.stamacasa.ro/evaluation/me

Expected: User should not be able to select future dates.

Actual: User is able to select any dates.

![future date](https://user-images.githubusercontent.com/47795680/80145105-f38b8700-85af-11ea-9ad5-1e1a14624f94.png)

**Comment by surdu** [comment]
This sounds like we need to use the min/max for the date/detetime inputs. We might want to implement this in the https://github.com/code4romania/taskforce-fe-components repo

**Comment by surdu** [comment]
@RaduCStefanescu Does it makes sense that the default to be NOT to be able to select dates in the future for all date fields, and have to specify explicitly in the question JSON when future dates are allowed? 

I'm fixing this in the shared components, so the scope of this question would be across all project.

**Comment by RaduCStefanescu** [comment]
Yes, default should be just today and past, but also we need an option to be able to say, choose dates in the future.
