### ISSUE TITLE
Only dates from current month should be highlighted

### ISSUE THREAD

**Issue by danaandres** [code4romania/stam-acasa#349]
Starting point: https://dev.stamacasa.ro/evaluation/me

Expected: The dates from other months should be greyed.

Actual: The user cannot distinguish the days of the current month.

![wrong display calendar](https://user-images.githubusercontent.com/47795680/80147209-7530e400-85b3-11ea-9bda-487a5f709250.png)

**Comment by surdu** [comment]
Same comment as https://github.com/code4romania/stam-acasa/issues/348#issuecomment-618806683

**Comment by surdu** [comment]
Fixed in https://github.com/code4romania/taskforce-fe-components/pull/167
