### ISSUE TITLE
Position of columns in Excel file containing results

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#357]
There are mismatches between the position of questions in the Excel file we send to authorities. The new user form and the follow up form contain a different number of questions, but they overlap on some ids. To make this work, we will need to maintain the same column in the excel file for questions with the same id: i.e. questionId = 3 on the same column

[20200424.xlsx](https://github.com/code4romania/stam-acasa/files/4528957/20200424.xlsx)

**Comment by idormenco** [comment]
will do

**Comment by bvizureanu** [comment]
How can someone test this?

**Comment by RaduCStefanescu** [comment]
On a local docker environment maybe?
I'll give it a try in an hour or so.

**Comment by idormenco** [comment]
@RaduCStefanescu @bvizureanu @catileptic i think this should be closed
