### ISSUE TITLE
Reversed placeholders/metadata on name and surname

### ISSUE THREAD

**Issue by bvizureanu** [code4romania/stam-acasa#360]
`name` and `surname` metadata on fields are reversed. Or the placeholders are;

*Surname* is defined as the family or last name.

![image](https://user-images.githubusercontent.com/3786565/80274797-a3164580-86e5-11ea-8ea4-a077829c553c.png)

**Comment by bvizureanu** [comment]
@RaduCStefanescu, @DragomirStefanaCatalina, can you please review this issue? is this valid?

**Comment by DragomirStefanaCatalina** [comment]
Placeholder reversal @bvizureanu 
 
name="nume" placeholder="Nume"
name="surname" placeholder="Prenume" 

![Screenshot 2020-04-25 at 11 42 01](https://user-images.githubusercontent.com/61550276/80275444-eb376700-86e9-11ea-9bb9-95142bf10448.png)

**Comment by bvizureanu** [comment]
so it should be the other way around, right? maybe some consistency in language use?
(`name` vs `nume`)

is it ok that the expected end state should be:

name=`name` placeholder=`Prenume`
name=`surname` placeholder=`Nume` | `Nume de familie` 
?

**Comment by DragomirStefanaCatalina** [comment]
@RaduCStefanescu your decision

**Comment by RaduCStefanescu** [comment]
> so it should be the other way around, right? maybe some consistency in language use?
> (`name` vs `nume`)
> 
> is it ok that the expected end state should be:
> 
> name=`name` placeholder=`Prenume`
> name=`surname` placeholder=`Nume` | `Nume de familie`
> ?

Yes, let's go with this one.
