### ISSUE TITLE
Add member form tab index

### ISSUE THREAD

**Issue by adascaliteiradu** [code4romania/stam-acasa#362]
Environment: https://dev.stamacasa.ro/add-member
## Problem
While navigating using `tab` in the add member form, the `Judet` and `Localitate` fields are not selected in the natural order. This might be an accessibility issue.

## How to test
Go to the `add-member` form. Select the `Nume` field and start navigating the form using tabs. When you reach the `Tip relatie` field and press tab once again, the next field that is selected is: `Varsta in ani impliniti` and should be `Judet`.

**Comment by idormenco** [comment]
@adascaliteiradu isn't this same as  #286 ?
