### ISSUE TITLE
Failed to open page for "Înregistrare"

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#363]
Starting point: http://localhost:5001/identity/account/register?returnUrl=https://stam-acasa.now.sh/register-complete

**Actual**:
Failed to open page for

> Înregistrare

![Screenshot 2020-04-25 at 13 04 12](https://user-images.githubusercontent.com/61550276/80277099-6ce0c200-86f5-11ea-95ed-f7be964d3aa4.png)

**Comment by RaduCStefanescu** [comment]
I think you are running this on https://stam-acasa.now.sh
Can you try the same operation on https://dev.stamacasa.ro ?

**Comment by DragomirStefanaCatalina** [comment]
sorry, my fault @RaduCStefanescu

**Comment by bvizureanu** [comment]
shall we close?
