### ISSUE TITLE
Login button doesn't respond 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#364]
Starting point: https://stam-acasa.now.sh

**Actual**:
Login button doesn't respond 

![Screenshot 2020-04-25 at 13 09 46](https://user-images.githubusercontent.com/61550276/80277271-846c7a80-86f6-11ea-8410-1c219006a251.png)

**Comment by bvizureanu** [comment]
that environment is not supposed to work. please only test on dev.stamacasa.ro

**Comment by DragomirStefanaCatalina** [comment]
sorry, my fault @bvizureanu
