### ISSUE TITLE
The user is allowed to pick future dates

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#365]
Starting point: https://dev.stamacasa.ro/evaluation/me

**Expected**:
The user is allowed to pick only past dates or the current date

**Actual**:
The user is allowed to pick future dates

![Screenshot 2020-04-25 at 13 16 15](https://user-images.githubusercontent.com/61550276/80277489-f4c7cb80-86f7-11ea-8452-893de16f9c0c.png)

![Screenshot 2020-04-25 at 13 16 31](https://user-images.githubusercontent.com/61550276/80277490-f8f3e900-86f7-11ea-88e3-56d5b26c2635.png)

![Screenshot 2020-04-25 at 13 16 46](https://user-images.githubusercontent.com/61550276/80277493-fbeed980-86f7-11ea-89aa-2dce22de0760.png)

![Screenshot 2020-04-25 at 13 17 01](https://user-images.githubusercontent.com/61550276/80277495-fe513380-86f7-11ea-9c31-e6ecbe0a6943.png)

![Screenshot 2020-04-25 at 13 17 15](https://user-images.githubusercontent.com/61550276/80277499-01e4ba80-86f8-11ea-9d4f-a62df7fc8669.png)

![Screenshot 2020-04-25 at 13 17 42](https://user-images.githubusercontent.com/61550276/80277503-05784180-86f8-11ea-8600-22308f7d0ca5.png)

![Screenshot 2020-04-25 at 13 17 56](https://user-images.githubusercontent.com/61550276/80277506-07da9b80-86f8-11ea-970e-4bf67a792f74.png)

**Comment by bvizureanu** [comment]
similar or duplicate with #348
