### ISSUE TITLE
Remove testing accounts for production

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#370]
On production environment, from https://prod.stamacasa.ro we still see the development testing accounts displayed - these need to be removed:
<img width="485" alt="Screenshot 2020-04-25 at 18 03 26" src="https://user-images.githubusercontent.com/15039873/80283283-16887900-871f-11ea-8c07-02661c38453d.png">

**Comment by aniri** [comment]
@RaduCStefanescu I think the test account should also be removed from the seed data, right? For the production env.

**Comment by surdu** [comment]
@RaduCStefanescu Unless I'm missing something, the registration process doesn't seem to work completely on develop (the email confirmation is not sent). How will devs create a test account ?

**Comment by idormenco** [comment]
in progress
