### ISSUE TITLE
Evaluation tabs scroll

### ISSUE THREAD

**Issue by adascaliteiradu** [code4romania/stam-acasa#375]
Environment: [https://dev.stamacasa.ro/evaluation/me](https://dev.stamacasa.ro/evaluation/me)
![image](https://user-images.githubusercontent.com/17283534/80285317-a254d200-872c-11ea-84ed-7d126586be91.png)

This UX problem happens at resolutions with a width between 1024px and 1215px

**Comment by aniri** [comment]
@moonflare is this one also fixed by your latest bug smash? :smiley:

**Comment by moonflare** [comment]
@aniri Possibly, but I haven't checked it specifically. Will assign it to me and check/fix it later tonight.

**Comment by moonflare** [comment]
> @aniri Possibly, but I haven't checked it specifically. Will assign it to me and check/fix it later tonight.

Fixed in #399

**Comment by aniri** [comment]
closing this as it was also fixed in #399
