### ISSUE TITLE
Error messages from register/login form should be in Romanian

### ISSUE THREAD

**Issue by aniri** [code4romania/stam-acasa#383]
![Screenshot from 2020-04-28 20-10-11](https://user-images.githubusercontent.com/1358055/80516569-556f3680-898c-11ea-9367-1ca8e0603413.png)

![Screenshot from 2020-04-28 20-11-33](https://user-images.githubusercontent.com/1358055/80516700-82bbe480-898c-11ea-87e8-cb576cceb86c.png)

**Comment by irinel-nistor** [comment]
I'd like to work on this one
