### ISSUE TITLE
Add password rules in register screen

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#417]
When a user creates his account, we give no information about what the password should contain (alpha numeric, special characters). We need to have a description of this on the registration page.

**Comment by cipick** [comment]
✋

**Comment by surdu** [comment]
@cipick 👈

**Comment by RaduCStefanescu** [comment]
@cipick do you have any updates on this one?

**Comment by cipick** [comment]
@RaduCStefanescu so sorry for the absence. i just checked the current behaviour on https://dev-is.stamacasa.ro/Identity/Account/Register and the backend returns the correct error message, do we want to have the validation on client too or we should add a paragraph under the form with the requirements?
<img width="506" alt="Screenshot 2020-06-18 at 17 30 30" src="https://user-images.githubusercontent.com/6429818/85033609-d3c8a780-b189-11ea-92b2-39a333006c6f.png">

**Comment by RaduCStefanescu** [comment]
Hi @cipick 
I think it would be better to have these rules static in the register screen, and not after the user inserts the password.
