### ISSUE TITLE
Delete account feature

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#418]
As an user of the platform I want to be able to delete my account. When a user deletes an account, all the data associated with that account will be deleted as well.

**Comment by irinel-nistor** [comment]
I'd like to work on this one

**Comment by surdu** [comment]
@irinel-nistor 🚀

**Comment by irinel-nistor** [comment]
I have some questions:
1. should there be an endpoint in the api that removes the forms, family members and self?
1.2. should the identity server page connect to the user db and delete all data (forms, family members and self)
2. should there be a page in identity server that would remove the user from the Identity server database?
3. should the page from the frontend application call both actions from above?
** there is a manage account section in IdentityServer, should we use that?
