### ISSUE TITLE
Fix data access in API

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#422]
Data leakage due to Insecure Direct Object Reference (IDOR) Vulnerability.

The application authorization functionality does not prevent one user from gaining access to another user's data or record by modifying (or by direct access of) the key value identifying the data. An attacker can retrieve or modify any submitted data by any other user of the application.

A. https://prod-api.stamacasa.ro/api/Profile?id=<id>
B. https://prod-api.stamacasa.ro/api/profile/family/<id>

**Comment by idormenco** [comment]
i will fix this
