### ISSUE TITLE
Email bombing 

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#426]
This vulnerability consists of sending numerous duplicate mails to the same email address with the goal of overflowing the mailbox and overwhelming the mail server hosting the address, making it into some form of denial of service attack.

https://prod-is.stamacasa.ro//identity/account/forgotPassword

Adding a timeout with the length of a few minutes after every request sending an email. Moreover, incrementing the length of timeout after a few(~3) requests to the same email.

**Comment by bogdanbujdea** [comment]
Sounds like exponential backoff could work here. A simple idea would be to add a field in the database for each user where we specify the next time after which they can request a new password.
For example:
1st request - send the email immediately, and set the db field to 3 minutes from now(let's say 12:03 PM)
2nd request - check if the current time is bigger than the one set in the db
if 3 minutes haven't passed, show a message like "You can try again after 12:03 PM" or "You can try again in x minutes and y seconds"
if 3 minutes or more have passed, send the email immediately, and set the field to now + 5 minutes
...
We can also define a maximum for the number of retries, which should be reset after each successful password reset.
If this approach is ok, I can get started on it.

**Comment by RaduCStefanescu** [comment]
Sounds exactly what we need @thewindev 
Go for it!

**Comment by bogdanbujdea** [comment]
Is this message ok? I have the implementation almost ready, we just need to discuss about the flow and establish exactly how many retries are allowed and the intervals between them.
![image](https://user-images.githubusercontent.com/793611/84608412-fec9a780-aeba-11ea-95e5-1f9db248242e.png)

**Comment by RaduCStefanescu** [comment]
The message looks great, but I think you should use diacritics.
