### ISSUE TITLE
View filled in forms on personal account

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#43]
**Prototype**
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=13%3A389

**Design**
<img width="591" alt="Screenshot 2020-03-26 at 23 30 34" src="https://user-images.githubusercontent.com/11520795/77698744-d0be8080-6fb9-11ea-8b2c-d0ff6cd9b8cd.png">

**Comment by chedydy** [comment]
rezervat.

**Comment by surdu** [comment]
This might be blocked by https://github.com/code4romania/taskforce-fe-components/issues/31

**Comment by tudorgergely** [comment]
@surdu https://github.com/code4romania/taskforce-fe-components/issues/31 got merged.

@chedydy still want this? :)

**Comment by RaduCStefanescu** [comment]
This one is already implemented in #126 
We can close it.
