### ISSUE TITLE
Email phishing through html injection in Name

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#433]
By using the IDOR, an attacker can change the information of any user, more importantly the name parameter, to contain a malicious HTML payload. Thus, as there are daily emails sent containing the user name, allow the attack to launch phishing attacks against all users registered.

`backend/src/StamAcasa.EmailService/EmailBuilder`

Properly sanitize input to not contain html code.

**Comment by idormenco** [comment]
in progress
