### ISSUE TITLE
Open Redirect Vulnerability

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#436]
Open redirection vulnerabilities arise when an application incorporates user-controllable data into the target of a redirection in an unsafe way. An attacker can construct a URL within the application that causes a redirection to an arbitrary external domain. This behavior can be leveraged to facilitate phishing attacks against users of the application. The ability to use an authentic application URL, targeting the correct domain and with a valid SSL certificate (if SSL is used), lends credibility to the phishing attack because many users, even if they verify these features, will not notice the subsequent redirection to a different domain.

Affected URL: prod-is.stamacasa.ro/Identity/Account/ConfirmEmail

Assume all input is malicious. Use an "accept known good" input validation strategy, i.e., use a whitelist of acceptable inputs that strictly conform to specifications. Reject any input that does not strictly conform to specifications, or transform it into something that does.

**Comment by idormenco** [comment]
on it
