### ISSUE TITLE
Strict transport security not enforced

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#439]
The application fails to prevent users from connecting to it over unencrypted connections. An attacker able to modify a legitimate user's network traffic could bypass the application's use of SSL/TLS encryption, and use the application as a platform for attacks against its users. This attack is performed by rewriting HTTPS links as HTTP, so that if a targeted user follows a link to the site from an HTTP page, their browser never attempts to use an encrypted connection. The sslstrip tool automates this process.

A. https://prod-is.stamacasa.ro 
B. https://prod.stamacasa.ro
C. https://prod-api.stamacasa.ro

The application should instruct web browsers to only access the application using HTTPS. To do this, enable HTTP Strict Transport Security (HSTS) by adding a response header with the name 'Strict-Transport-Security' and the value 'max-age=expireTime', where expireTime is the time in seconds that browsers should remember that the site should only be accessed using HTTPS. Consider adding the 'includeSubDomains' flag if appropriate.

**Comment by idormenco** [comment]
insetigating
