### ISSUE TITLE
User enumeration using email brute force

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#440]
Username enumeration is the process of developing a list of all valid usernames on a server or web application. It becomes possible if the server or application provides a clue as to whether or not the username exists.

Affected URL: https://prod-is.stamacasa.ro/Identity/Account/RegisterConfirmation

Developers need to take precautions with any public-facing page which uses username, email, or any other user identifier for any purpose.
If the page accepts a user identifier as input, then the output must not indicate if the user exists or not. This output includes not only the message returned to the user, but changes to the page contents (HTML, CSS, images, form structure or values), URL, or even cookie data.

**Comment by idormenco** [comment]
this might help somenone to fix this.
https://blog.rapid7.com/2017/06/15/about-user-enumeration/

**Comment by idormenco** [comment]
To change the messages returned by identity server this is useful https://stackoverflow.com/questions/19961648/how-to-localize-asp-net-identity-username-and-password-error-messages
