### ISSUE TITLE
Update site content

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#443]
**Hero area**
Replace this:
Ești izolat la domiciliu iar telefoanele de urgență sunt împovărate de numărul mare de apeluri, făcând astfel evaluarea situațiilor medicale la nivel național o problemă reală. Toți suntem în aceeași situație.
Stăm acasă este o soluție digitală cu ajutorul căreia, împreună, reducem suprasolicitarea numerelor de urgență, colectăm rapid informații de la o populație foarte mare, ne monitorizăm starea de sănătate pentru noi și pentru cei dragi.

With this: 
Starea de alertă poate fi dificil de gestionat. Avem din nou voie să ieșim din casă, dar urmând proceduri și reguli foarte clare. Riscul de a contracta virusul este foarte ridicat și este important să putem să ne monitorizăm starea cu ușurință și, de asemenea, este util să ne menținem un jurnal al ieșirilor. Telefoanele de urgență sunt împovărate de numărul mare de apeluri, făcând astfel evaluarea situațiilor medicale la nivel național o problemă reală. Toți suntem în aceeași situație.
Jurnal Medical este o soluție digitală cu ajutorul căreia, împreună, reducem suprasolicitarea numerelor de urgență, colectăm rapid informații de la o populație foarte mare, ne monitorizăm starea de sănătate pentru noi și pentru cei dragi și rămânem cu toții în siguranță.

**Despre**
Replace this
Ești izolat la domiciliu iar telefoanele de urgență sunt împovărate de numărul mare de apeluri, făcând astfel evaluarea situațiilor medicale la nivel național o problemă reală. Oare câți alții ca tine sunt în situația ta?
Stăm Acasă este o soluție digitală cu ajutorul căreia reducem suprasolicitarea numerelor de urgență, colectăm rapid informații de la o populație foarte mare și vom facilita astfel o evaluare constantă oferind sprijin în managementul cazurilor pentru autorități.
Stăm Acasă este un proiect dezvoltat în parteneriat cu Guvernul României prin Autoritatea pentru Digitalizarea României, cu colaborarea Ministerului Sănătății, de către organizația Code for Romania, în cadrul programului Code for Romania Task Force.

With this:
Starea de alertă poate fi dificil de gestionat. Avem din nou voie să ieșim din casă, dar urmând proceduri și reguli foarte clare. Riscul de a contracta virusul este foarte ridicat și este important să putem să ne monitorizăm starea cu ușurință și, de asemenea, este util să ne menținem un jurnal al ieșirilor. Telefoanele de urgență sunt împovărate de numărul mare de apeluri, făcând astfel evaluarea situațiilor medicale la nivel național o problemă reală. Toți suntem în aceeași situație.
Jurnal Medical este o soluție digitală cu ajutorul căreia, împreună, reducem suprasolicitarea numerelor de urgență, colectăm rapid informații de la o populație foarte mare, ne monitorizăm starea de sănătate pentru noi și pentru cei dragi și rămânem cu toții în siguranță.
 
Jurnal Medical este un proiect dezvoltat în parteneriat cu Guvernul României prin Autoritatea pentru Digitalizarea României, cu colaborarea Ministerului Sănătății, de către organizația Code for Romania, în cadrul programului Code for Romania Task Force. Proiectul este administrat de Autoritatea pentru Digitalizarea României. 

**Footer**
Add the following links: 
Despre proiect
Ministerul Sănătății
Guvernul României
Autoritatea pentru Digitalizarea României
Institutul Național de SănătatePublică
Termeni și condiții

**Comment by andorremus** [comment]
I'll take this

**Comment by andorremus** [comment]
linkuri pt footer?

**Comment by RaduCStefanescu** [comment]
@andorremus sorry, I missed your comment
Despre proiect -> `/despre`
MS -> http://www.ms.ro/
https://www.gov.ro/
https://www.adr.gov.ro/
https://www.insp.gov.ro/
`/termeni-si-conditii`
