### ISSUE TITLE
Create email service

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#50]
Part of the platform, we need to send emails in 2 situations:
- when an user creates an account
- when a daily notification needs to be sent to the user to complete his assessment
- when sending the daily notification to institutions

We need to have an email service that will use a SMTP server, that will be part of the deployment.
The email service needs to be configurable (details need to be in appsettings.json)
The email service will have to use 2 templates, for the 2 situations detailed earlier.

The email service consumes requests via rabbitMQ.
A request will contain the following information:
- the email address where we will be sending the email
- a key-value list with the tokens that need to be merged with the email template
- a document that will be sent as attachment in the email, if this is the case

**Comment by cristianMardare** [comment]
I can take this issue
