### ISSUE TITLE
User isn't logged out after deleting the account

### ISSUE THREAD

**Issue by catileptic** [code4romania/stam-acasa#504]
After a user enters their password and clicks the button to delete their account, the application should log them out and redirect them to the landing page. 

Right now, on Firefox, the user deletes their account and the application does not log them out afterwards. 
It would seem like, on Safari, the application does log them out - but then again, I'm probably one of the few unfortunate ones still using Safari.  

If I log myself out, on Firefox, and then try to log back in with the credentials tied to the account I just deleted, the log in fails - as expected. 

Let's fix this by logging the user out after they delete their account and redirecting them to the landing page.

**Comment by idormenco** [comment]
on it
