### ISSUE TITLE
Create notification service

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#51]
Each user needs to receive a daily email that prompts him to login and fill in an assessment for himself and the people in his care.

We need to write a service that daily will pick up the list of users in the platform and generate requests to the Email service for sending the assessment email.

The requests will be sent via RabbitMQ.

**Comment by cosminpopescu14** [comment]
As dori eu sa ma ocup de el :)

**Comment by marculescu** [comment]
Please see the updated to-do list in [this comment](https://github.com/code4romania/stam-acasa/issues/51#issuecomment-605424008).

----

We devised the following to-do list:

- [ ] Add IUserService.GetUsers() and implementation in UserService.GetUsers()
- [ ] Define Request class and build it from User
- [ ] Send a request to the Email service using RabbitMQ
- [ ] Create interface IAssessmentNotifications with one method: Task GenerateRequests()
- [ ] Create an implementation for GenerateRequests()
- [ ] Configure the IServiceCollection DI with the implementations above
- [ ] Setup daily scheduling for invoking IAssessmentNotifications.GenerateRequests()

**Comment by RaduCStefanescu** [comment]
Sounds great, but I have a few comments to make:
- Request class - this is a DTO, let's keep it outside of any service definition
- we have more then 1 type of Notifications to be generated - I would create a generic Notification interface and several implementations for it
- I would actually also create a class that gets all the implementations of the Notification interface injected in the container and schedule them (this is not mandatory, it would be a nice to have feature)

Let me know what you think about this!

**Comment by marculescu** [comment]
- I thought about making the Request class a "smart" one, with the responsibility to invoke the RabbitMQ itself and place itself on the queue (or maybe a RequestDto, as you mention). But I'm ok also with just the Dto approach.
- _generic Notification_: ok, though it's not clear now for me what will the common Notification behavior be
- _a class that gets all the implementations of the Notification interface_: I discussed with @cosminpopescu14 about the schedule itself, we don't know who will be responsible for actually running the job (for instance, is there a web job attached to the web app, like in Azure web jobs?)

**Comment by marculescu** [comment]
Here's an update list of tasks, based on the comments above:

- [x] Add IUserService.GetUsers() and implementation in UserService.GetUsers()
- [x] Create interface IQueue with 2 methods: Queue(INotification), Task<INotification> Dequeue()
- [x] Create interface INotification
- [x] Create INotification implementation AssesmentNotification(User)
- [x] Add INotificationsDispatch interface with a Process() method and an implementation AssessmentNotificationsDispatch that retrieves the users, creates AssessmentNotifications and queue them
- [x] Create an implementation of IQueue that uses RabbitMQ
- [ ] Configure the IServiceCollection DI with the implementations above
- [ ] Get all the implementations of the INotification interface injected in the container

**Comment by marculescu** [comment]
@RaduCStefanescu, we need some clarifications please.

Where should this service be instantiated?

At the moment we have an interface called `INotificationsDispatch` and an implementation called `AssessmentNotificationsDispatch`, with a Process() method that retrieves the users, creates assessment notifications and queues them.
AssessmentNotificationsDispatch is built with this ctor: `AssessmentNotificationsDispatch(IUserService userService, IQueue queue)`.

I guess we don't instantiate it in the Api.Startup, but in a separate project like a web job, that will run on a schedule and invoke the Process() method, right?

Also, is instantiating the service in the scope of this task?

Thanks.
