### ISSUE TITLE
User can't delete account on Firefox

### ISSUE THREAD

**Issue by catileptic** [code4romania/stam-acasa#511]
Dacă vă faceți cont pe dev.stamacasa.ro folosind Firefox și încercați să-l ștergeți, o să:

- apară un mesaj temporar sub butonul de ștergere care zice "încercarea de ștergere a contului a eșuat"
- fiți redirectați către aceeași pagină, de account deletion, fără să vi se ștergă contul
- obervați, în Inspector, ca POST-ul pe https://dev-is.stamacasa.ro/account/delete apare Blocked (la mine în Firefox se reproduce totdeauna din a doua încercare. la prima încercare nu-mi apare deloc POST-ul ăla)

**Comment by paul-antal** [comment]
Problema pare sa fie ca button-ul de delete nu are type pus pe el si e intr-un form.

Un button are by default type submit
Daca apesi pe un button de tip submit care e intr-un form, face submit la form.
Submit-ul la form reincarca pagina.
Daca pagina face refresh, automat toate request-urile deschise sunt anulate si apar ca "request failed".
Am impresia ca se trimite si un fel de "cancel spre server, but I'm not so sure about that.

Am verificat pe firefox si am editat putin html-ul in dev tools, si a mers.

Maybe further testing needed (as verifica daca intra macar in metoda din controller).
(Banui ca IE si Chrome ori nu anuleaza, ori override-ul pe submit le face sa nu faca submit)

(Testeaza @idormenco acuma)
