### ISSUE TITLE
Assessment answers service

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#53]
When a user completes an assessment for himself or his family members, a JSON is sent from the frontend to the backend. The assessment must expose an endpoint where this information is received.
The service will write this JSON to disk so that it can be indexed by Elasticsearch.
The service will also write the data redundantly in an SQL database in order to be able to serve the history of assessments per user.

**Comment by andreimole** [comment]
Salutare pot sa iau eu asta?

**Comment by RaduCStefanescu** [comment]
yes please!

**Comment by RaduCStefanescu** [comment]
This issue is related to #81 
The Postgres database will be used to retain these answers in a simple format:
- user id
- timestamp
- answer in JSON format
@bvizureanu any other fields we should pesist?

**Comment by RaduCStefanescu** [comment]
This issue is already covered by the FormsController and FormsService.
Will close it.
