### ISSUE TITLE
Display history of filled in assessments in user profile

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#54]
As an user I want to be able to view the history of filled in assessments on my profile.
![Contul meu - formularele mele](https://user-images.githubusercontent.com/15039873/77794154-0e7fdf80-7074-11ea-86d1-445a7c7f71c3.png)

We need to integrate this component from the frontend components when it is done: https://github.com/code4romania/taskforce-fe-components/issues/31

**Comment by adaczo** [comment]
Salut, as dori sa incep acest task

**Comment by RaduCStefanescu** [comment]
This issue is handled in #126 that we just closed. 
Will close this one as well.
