### ISSUE TITLE
Create Excel document service

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#55]
Daily we need to send a document that contains all the flagged cases that were discovered during the day to a set of predefined email addresses.

We need to create an excel document service, that receives a list of answers, in JSON format and generates an excel file.

**Comment by MarinelMarian** [comment]
I'd like to try helping on this one

**Comment by tedchirvasiu** [comment]
I could try to help generating the Excel file using NPOI and send the mails via MailKit. What's the required structure of the Excel file?
