### ISSUE TITLE
Create Scheduling service

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#64]
As part of the platform we need to send emails on a daily basis.
We need a scheduling service that will invoke the notification service for sending these emails.

The scheduler needs to send:
- daily emails to users for assessments in the morning
- daily emails to a predefined set of email addresses

**Comment by bvizureanu** [comment]
what did you have in mind for this?

**Comment by RaduCStefanescu** [comment]
Scheduler schedules tasks -> Notification service selects users -> Email service sends emails

that would be an oversimplification of the process I had in mind

**Comment by abalaci** [comment]
Is anyone looking into this? I'd like to help out if it's still up for grabs.

**Comment by RaduCStefanescu** [comment]
Yes, this one is still up for grabs @abalaci
