### ISSUE TITLE
Create different environment for dev vs. prod

### ISSUE THREAD

**Issue by surdu** [code4romania/stam-acasa#85]
We need to be able to configure two separate environments: one for development and one for production. This way we can configure the URL for the back-end differently in-between these two deployments.

**Comment by tudorgergely** [comment]
is the backend on a different server/endpoint or can we use the proxy feature for this? https://create-react-app.dev/docs/proxying-api-requests-in-development/

**Comment by surdu** [comment]
@tudorgergely If I'm understanding correctly, this will work only for API calls. We will need this variable to also compose some URLs that are handled completely on the back-end side, like the link to register/login/logout.

**Comment by surdu** [comment]
This should have been fixed in #104
