### ISSUE TITLE
Add family member improvements

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#94]
As a user I want to be able to add a family member to my account:
- enhance `legatura familiala` with all the possbile values - including `persoana in grija`
- enhance `Varsta` to be text entry only accepting numbers as input
- enhance `conditii de sanatate preexistente` with a multiple select list (we will provide the elements)
- `Da/Nu` in `Are anumite dizabilitati` should be single select only
- when choosing `Da` a text entry should be made visible to insert values
- reduce the spacing between the question and the possible answers
- change the button color and size to match the UX

**Comment by acraileanu** [comment]
Not a FE guy but I can give it a go - are the options for `legatura familiala` and `conditii de sanatate preexistente` available somewhere?

**Comment by RaduCStefanescu** [comment]
`legatura familiala`
- parinte
- fiu/fiica
- frate/sora
- alt membru al familiei
- persoana in grija

`conditii preexistente`
- boala cardiovasculara
- diabet
- boala pulmonara
- cancer
- alta boala cronica

**Comment by acraileanu** [comment]
Added a PR, but not really sure in terms of quality, since I am not familiar with React, nor with UX touch.
