### ISSUE TITLE
Personal assesment form improvements

### ISSUE THREAD

**Issue by surdu** [code4romania/stam-acasa#98]
The following improvements are needed for assessment form:
 - [ ] Get form data from API
 - [ ] Create authenticated routes (the user can see data only if it is logged in)

This is a continuation of #18

**Comment by tudorgergely** [comment]
I'll take this if you still need help :)

**Comment by surdu** [comment]
@tudorgergely All yours ;)

**Comment by tudorgergely** [comment]
@surdu totally forgot about this. What is actually left? we have authenticated routes, what data do we need to get from the API?

**Comment by RaduCStefanescu** [comment]
I just pushed a PR that exposes a new endpoint on `/api/form/version`
The frontend needs to get the forms from this endpoint.
